"""
report.py — Auto-generates a Markdown summary report of the run.
"""

import os
from datetime import datetime
from config import OUTPUTS_DIR

os.makedirs(OUTPUTS_DIR, exist_ok=True)


def generate_report(metrics: dict, cv_summary: dict, feature_names: list) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# XGBoost Diabetes Prediction — Run Report",
        f"**Generated:** {now}  ",
        "",
        "---",
        "",
        "## Dataset",
        "- **Source:** Pima Indians Diabetes Database (UCI / GitHub Jbrownlee)",
        "- **Rows:** 768  |  **Features:** 8 (+ 3 engineered)  |  **Target:** Outcome (binary)",
        "- **Positive class:** ~34.9 %",
        "",
        "---",
        "",
        "## Cross-Validation Results (Stratified 5-Fold)",
        "",
        "| Metric | Mean | Std |",
        "|--------|------|-----|",
    ]

    for metric, vals in cv_summary.items():
        lines.append(f"| {metric} | {vals['mean']:.4f} | {vals['std']:.4f} |")

    lines += [
        "",
        "---",
        "",
        "## Test Set Results",
        "",
        "| Metric | Score |",
        "|--------|-------|",
    ]

    for metric, value in metrics.items():
        lines.append(f"| {metric} | {value:.4f} |")

    lines += [
        "",
        "---",
        "",
        "## Features Used",
        "",
        "| # | Feature |",
        "|---|---------|",
    ]
    for i, f in enumerate(feature_names, 1):
        lines.append(f"| {i} | {f} |")

    lines += [
        "",
        "---",
        "",
        "## Plots Generated",
        "",
        "| File | Description |",
        "|------|-------------|",
        "| 01_class_distribution.png     | Bar + Pie: outcome balance |",
        "| 02_feature_distributions.png  | Histograms by class |",
        "| 03_correlation_heatmap.png    | Pearson correlation matrix |",
        "| 04_boxplots.png               | Boxplots by class |",
        "| 05_confusion_matrix.png       | Confusion matrix (test set) |",
        "| 06_roc_curve.png              | ROC curve with AUC |",
        "| 07_precision_recall.png       | PR curve with average precision |",
        "| 08_feature_importance.png     | XGBoost gain importance |",
        "| 09_probability_distribution.png | Predicted probability histograms |",
        "| 10_shap_summary.png           | SHAP beeswarm plot |",
        "| 11_metrics_dashboard.png      | Combined metrics dashboard |",
        "",
        "---",
        "",
        "*Report auto-generated by `report.py`*",
    ]

    content = "\n".join(lines)
    path = f"{OUTPUTS_DIR}/report.md"
    with open(path, "w") as f:
        f.write(content)

    print(f"[Report] Saved → {path}")
    return path
